---
# handlers file for ansible-geonode
- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  sudo: yes

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart uwsgi
  service: name=uwsgi state=restarted
  sudo: yes
