---
# handlers file for ansible-geonode
- name: Restart rabbitmq
  service: 
    name: rabbitmq-server 
    state: restarted
  sudo: yes

- name: Restart nginx
  service: 
    name: nginx 
    state: restarted
  sudo: yes

- name: Restart uwsgi
  service: 
    name: uwsgi 
    state: restarted
  sudo: yes

- name: Restart elasticsearch
  service: 
    name: elasticsearch 
    state: restarted
    enabled: yes
  sudo: yes