- hosts: production 
  remote_user: vagrant
  vars:
    app_name: piensanode
    github_user: piensa
    server_name: 192.168.56.151
    deploy_user: vagrant
  roles:
     - { role: ansible-geonode }
