- name: ensure supervisor package is installed
  apt: name=supervisor
  sudo: yes

- name: Import Elastic GPG Key
  shell: "wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"
  sudo: yes
  tags: [elasticsearch]

- name: add elasticsearch repository
  apt_repository: repo='deb https://packages.elastic.co/elasticsearch/{{ es_version }}/debian stable main' state=present
  tags: [elasticsearch]

- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes  cache_valid_time=7200
  sudo: yes 
  tags: [elasticsearch]

- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'
  sudo: yes
  tags: [elasticsearch]

- name: update
  shell: apt-get update
  sudo: yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes
  tags: [elasticsearch]

- name: install java8
  shell: apt-get install -y oracle-java8-installer ca-certificates
  sudo: yes

- name: install elasticsearch
  apt: name=elasticsearch state=present update_cache=yes cache_valid_time=7200
  notify: init elasticsearch
  tags: [elasticsearch]

- name: set heap size
  lineinfile: dest=/etc/default/elasticsearch regexp='^ES_HEAP_SIZE' line="ES_HEAP_SIZE={{ es_heap_size }}" state=present
  tags: [elasticsearch]

- name: Updating ES config
  copy: src=elasticsearch.conf.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: start elasticsearch service
  service: name=httpd state=restarted
  tags: [elasticsearch]


