###
# Installs nginx 
#
---
- name: add repository for latest nginx stable
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes

- name: ensure nginx is installed
  apt: name=nginx update_cache=yes cache_valid_time=7200
  sudo: yes

- name: write nginx configuration for multiple subdomains
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  sudo: yes
  notify:
    - restart nginx
